on:
  push:
    branches: [ main ]
    paths: [ '**.go' ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Install go on Amazon Linux 2
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Build go server
        run: go build -o server main.go
      - name: Deploy to Server 1
        run: rsync -avz -e "ssh -i ${{ secrets.EC2_SSH_KEY }}" server ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}