name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: amazon-linux-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@34.201.245.69 'bash -s' < deploy.sh