name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build
        run: go build -v
    
  # create a deploy job that uses docker on the ec2 instance to deploy the app
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
        id: go

      - name: Build
        run: go build -v

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 8080
          source: "main"
          target: "/home/ubuntu"
          strip_components: 1
          args: "-o StrictHostKeyChecking=yes"