name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build
        run: go build -v
    
  # create a deploy job that uses docker on the server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go

      - name: Build
        run: go build -v

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ''
          port: 8080
          script: |
            cd /home/ubuntu
            ./deploy.sh
  