name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install AWS CLI
        run: sudo apt install awscli

      - name: Configure AWS credentials
        run: |
          echo 'export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' >> ~/.bashrc &&
          echo 'export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' >> ~/.bashrc

      - name: Build Docker image
        run: docker build -t code-snippet-manager .

      - name: Deploy to AWS EC2
        run: |
          aws ec2 run-instances \
            --image-id ami-0123456789abcdef \
            --instance-type t2.micro \
            --security-group-ids sg-0123456789abcdef \
            --count 1 \
            --user-data file://user-data.sh