# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd /projects/code-snippet-manager && git pull"
        echo "Deploying the app"
        sudo docker build -t go-app .
        sudo docker run -d -p 8080:8080 go-app
    


